version: '3.9'

services:
  mysql:
    container_name: mysql
    build:
      context: ./docker/mysql
      dockerfile: Dockerfile
    volumes:
      - ./db:/var/lib/mysql
      - ./initdb.d:/docker-entrypoint-initdb.d
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: database
      MYSQL_USER: develop
      MYSQL_PASSWORD: password
    healthcheck:
     test: mysqladmin ping -h localhost -u $$MYSQL_USER -p$$MYSQL_PASSWORD

  schemaspy:
    container_name: schemaspy
    build:
      context: ./docker/schemaspy
      dockerfile: Dockerfile
    volumes:
      - ./schemaspy/schemaspy.properties:/schemaspy.properties
      - ./output:/output
    tty: true
    depends_on:
      mysql:
        condition: service_healthy
    environment:
      SCHEMASPY_OUTPUT: /output
