version: '3.9'

services:
  mysql:
    container_name: mysql
    image: mysql:8
    volumes:
      - ./db:/var/lib/mysql
      - ./initdb.d:/docker-entrypoint-initdb.d
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: database
      MYSQL_USER: develop
      MYSQL_PASSWORD: password
    healthcheck:
     test: ["CMD", "mysqladmin" ,"ping", "-h", "localhost", "-u", "develop", "-pdevelop"]

  schemaspy:
    container_name: schemaspy
    image: schemaspy/schemaspy:snapshot
    volumes:
      - ./schemaspy/schemaspy.properties:/schemaspy.properties
      - ./output:/output
    tty: true
    environment:
      SCHEMASPY_OUTPUT: /output
